version: '3'
services:
  backend:
    build:
      context: ./demo
      dockerfile: Dockerfile
    image: frontendreact
    container_name: frontendreact
    ports:
      - 8080:8080

  frontend:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    image: backendjava
    container_name: backendjava
    ports:
      - '5000:80'
    depends_on:
      - backend
