version: '3'
services:
  
  backend:
    build:
      context: ./demo
      dockerfile: Dockerfile
    image: backendjava
    container_name: backendjava
    ports:
      - 8080:8080

  frontend:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    image: frontreact
    container_name: frontreact
    ports:
      - '5000:80'
    depends_on:
      - backend

  chrome:
    image: selenium/node-chrome:4.0.0-rc-1-prerelease-20210618
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - '5900'
    depends_on: 
      - backend
      - frontend

  selenium-hub:
    image: selenium/hub:4.0.0-rc-1-prerelease-20210618
    container_name: selenium-hub
    ports:
      - '4442:4442'
      - '4443:4443'
      - '4444:4444'
    depends_on: 
      - backend
      - frontend
  
  # bdd:
  #   build:
  #     context: ./bdd
  #     dockerfile: Dockerfile
  #   image: bdd
  #   container_name: bddcontainer
  #   depends_on:
  #     - backend
  #     - frontend
  #     # - selenium-hub
  #     - chrome